# To rebuild and publish this container run:
#   gcloud container builds submit --config update_build_container.yaml .

FROM debian
RUN apt-get -q update && apt-get install -qqy curl git python wget

# Install Repo tool
RUN curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/local/bin/repo && \
    chmod a+x /usr/local/bin/repo
